[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "JAEmLvmg375QVveG8FRzG5arXeo4fadtG4qceGsJPAKB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/adromedemon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
